// Generated by ReScript, PLEASE EDIT WITH CARE

import * as KoreanNumeral_test from "./specs/KoreanNumeral_test.mjs";

let testEqual = KoreanNumeral_test.testEqual;

export {
  testEqual,
}
/* KoreanNumeral_test Not a pure module */
